### ISSUE TITLE
whitelisted cachix push and pins

### ISSUE THREAD

**Issue by sinrohit** [juspay/cachix-push#10]
Caches with limited storage could exhaust the storage if we push and pin every flake outputs of a subflake. Hence there should be an option to  do a whitelisted push and pin.

For example I only want to push and pin `omnix-cli` and `omnix-devshell` 

![Screenshot 2024-11-07 at 4 07 18 PM](https://github.com/user-attachments/assets/a6668c75-3392-4f9f-8c46-bcdf0cfa0d75)

**Comment by srid** [comment]
> Caches with limited storage could exhaust the storage if we push and pin every flake outputs of a subflake.

Can you think of a concrete example (perhaps an internal project) where this would be the case?
